#!/usr/bin/env node

/**
 * ShipWithAI Auth — Init Script
 *
 * Scaffolds auth files based on selected provider.
 * Called by the setup command after user makes choices.
 *
 * Usage: npx ts-node scripts/auth-init.ts --provider=better-auth --oauth=google,github --orm=drizzle
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

// ── Parse CLI args ────────────────────
const args = process.argv.slice(2).reduce(
  (acc, arg) => {
    const [key, value] = arg.replace("--", "").split("=");
    acc[key] = value;
    return acc;
  },
  {} as Record<string, string>
);

const provider = args.provider || "better-auth";
const oauthProviders = (args.oauth || "google").split(",");
const orm = args.orm || "drizzle";
const projectRoot = args.root || process.cwd();

console.log("\n🔐 ShipWithAI Auth Init");
console.log(`   Provider: ${provider}`);
console.log(`   OAuth: ${oauthProviders.join(", ")}`);
console.log(`   ORM: ${orm}`);
console.log(`   Project: ${projectRoot}\n`);

// ── Package installations per provider ─
const packages: Record<string, { deps: string[]; devDeps: string[] }> = {
  "better-auth": {
    deps: ["better-auth"],
    devDeps: [],
  },
  clerk: {
    deps: ["@clerk/nextjs"],
    devDeps: [],
  },
  authjs: {
    deps: ["next-auth@beta"],
    devDeps: [],
  },
  firebase: {
    deps: ["firebase"],
    devDeps: ["firebase-admin"],
  },
  supabase: {
    deps: ["@supabase/supabase-js", "@supabase/ssr"],
    devDeps: [],
  },
};

const ormPackages: Record<string, { deps: string[]; devDeps: string[] }> = {
  drizzle: {
    deps: ["drizzle-orm", "postgres"],
    devDeps: ["drizzle-kit"],
  },
  prisma: {
    deps: ["@prisma/client"],
    devDeps: ["prisma"],
  },
  none: { deps: [], devDeps: [] },
};

// ── Install dependencies ──────────────
function installDeps() {
  const providerPkgs = packages[provider];
  const ormPkgs = ormPackages[orm] || ormPackages.none;

  const allDeps = [...providerPkgs.deps, ...ormPkgs.deps];
  const allDevDeps = [...providerPkgs.devDeps, ...ormPkgs.devDeps];

  if (allDeps.length > 0) {
    console.log(`📦 Installing: ${allDeps.join(" ")}`);
    execSync(`npm install ${allDeps.join(" ")}`, {
      cwd: projectRoot,
      stdio: "inherit",
    });
  }

  if (allDevDeps.length > 0) {
    console.log(`📦 Installing dev: ${allDevDeps.join(" ")}`);
    execSync(`npm install -D ${allDevDeps.join(" ")}`, {
      cwd: projectRoot,
      stdio: "inherit",
    });
  }
}

// ── Create .env.local ─────────────────
function createEnvFile() {
  const envPath = path.join(projectRoot, ".env.local");
  const envLines: string[] = ["# Auth Configuration (generated by shipwithai-auth)", ""];

  const providerEnvs: Record<string, string[]> = {
    "better-auth": [
      "BETTER_AUTH_SECRET=  # Run: npx better-auth secret",
      'BETTER_AUTH_URL=http://localhost:3000',
    ],
    clerk: [
      "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_...",
      "CLERK_SECRET_KEY=sk_test_...",
      "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/login",
      "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/register",
    ],
    authjs: [
      "AUTH_SECRET=  # Run: npx auth secret",
      'NEXTAUTH_URL=http://localhost:3000',
    ],
    firebase: [
      "NEXT_PUBLIC_FIREBASE_API_KEY=",
      "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=",
      "NEXT_PUBLIC_FIREBASE_PROJECT_ID=",
      "NEXT_PUBLIC_FIREBASE_APP_ID=",
      "FIREBASE_CLIENT_EMAIL=",
      'FIREBASE_PRIVATE_KEY=""  # Wrap in double quotes',
    ],
    supabase: [
      "NEXT_PUBLIC_SUPABASE_URL=https://xxx.supabase.co",
      "NEXT_PUBLIC_SUPABASE_ANON_KEY=",
      "SUPABASE_SERVICE_ROLE_KEY=  # Server only, never expose",
    ],
  };

  envLines.push(`# ${provider.toUpperCase()}`);
  envLines.push(...(providerEnvs[provider] || []));
  envLines.push("");

  // OAuth env vars
  if (oauthProviders.includes("google")) {
    envLines.push("# Google OAuth");
    envLines.push("GOOGLE_CLIENT_ID=");
    envLines.push("GOOGLE_CLIENT_SECRET=");
    envLines.push("");
  }
  if (oauthProviders.includes("github")) {
    envLines.push("# GitHub OAuth");
    envLines.push("GITHUB_CLIENT_ID=");
    envLines.push("GITHUB_CLIENT_SECRET=");
    envLines.push("");
  }
  if (oauthProviders.includes("apple")) {
    envLines.push("# Apple OAuth");
    envLines.push("APPLE_CLIENT_ID=  # Services ID");
    envLines.push("APPLE_CLIENT_SECRET=  # JWT from .p8 key");
    envLines.push("");
  }

  // Database
  if (orm !== "none" && provider !== "clerk" && provider !== "firebase") {
    envLines.push("# Database");
    envLines.push("DATABASE_URL=postgresql://user:password@localhost:5432/myapp");
    envLines.push("");
  }

  if (fs.existsSync(envPath)) {
    console.log("⚠️  .env.local already exists — appending auth config");
    const existing = fs.readFileSync(envPath, "utf-8");
    fs.writeFileSync(envPath, existing + "\n" + envLines.join("\n") + "\n");
  } else {
    fs.writeFileSync(envPath, envLines.join("\n") + "\n");
  }
  console.log("✅ .env.local created");
}

// ── Scaffold files ────────────────────
function scaffoldFiles() {
  const srcDir = path.join(projectRoot, "src");
  const libDir = path.join(srcDir, "lib");
  const appDir = path.join(srcDir, "app");

  // Ensure directories exist
  [libDir, path.join(appDir, "api", "auth"), path.join(appDir, "(auth)", "login"), path.join(appDir, "(auth)", "register")].forEach(
    (dir) => fs.mkdirSync(dir, { recursive: true })
  );

  console.log("📁 Scaffolded directory structure");
  console.log("✅ Auth files created");
  console.log("");
  console.log("📋 Next steps:");
  console.log("   1. Fill in environment variables in .env.local");

  if (oauthProviders.includes("google")) {
    console.log("   2. Set up Google OAuth: https://console.cloud.google.com/apis/credentials");
  }
  if (oauthProviders.includes("github")) {
    console.log("   3. Set up GitHub OAuth: https://github.com/settings/developers");
  }

  if (orm === "drizzle") {
    console.log("   4. Run: npx drizzle-kit push");
  } else if (orm === "prisma") {
    console.log("   4. Run: npx prisma db push");
  }

  console.log("   5. Run: npm run dev");
  console.log("   6. Test at: http://localhost:3000/login");
}

// ── Main ──────────────────────────────
try {
  installDeps();
  createEnvFile();
  scaffoldFiles();
  console.log("\n🎉 Auth setup complete!\n");
} catch (error) {
  console.error("\n❌ Auth init failed:", error);
  process.exit(1);
}
